### ISSUE TITLE
[Enhancment] Display Icon or Information if an addon is not up to date

### ISSUE THREAD

**Issue by b00nation** [Idrinth/WARAddonClient#123]
If possible add an icon to the table to display, if an addon is not up to date.

**Comment by Idrinth** [comment]
right now not up to date is shown with an X

**Comment by Idrinth** [comment]
@b00nation is the X insufficient?

**Comment by b00nation** [comment]
yes sure will try the new version. Thank you

**Comment by Idrinth** [comment]
just reopen it if it's not ok :)
