### ISSUE TITLE
Add gradle build tools, along with unit tests

### ISSUE THREAD

**Issue by Bryman** [Idrinth/WARAddonClient#168]
Are you open to switching from maven to gradle, or at least adding the maven wrapper so maven doesn't need to be installed on local machines?

What is your stance on adding some unit tests?

**Comment by Idrinth** [comment]
I would like to stay with maven, it's pretty much a given for any IDE to bring it along anyway. I'd be happy about unittests, just haven't had time to write any myself yet.
