### ISSUE TITLE
Sort outdated

### ISSUE THREAD

**Issue by Firzum** [Idrinth/WARAddonClient#28]
Hello,

Many thanks for this application.
Is it possible to add a sorting by version status (not up to date) ?

Thanks in advance !

Regards

**Comment by Idrinth** [comment]
Hi Firzum,
Thanks for the idea.
It certainly is, wasn't sure this application was even in use. Will have a look soon, likely before the weekend.

**Comment by Firzum** [comment]
Many thanks Idrinth.
Don't stress too much, trhis is not as urgent =D

**Comment by pskmsc** [comment]
Thanks you so much !

**Comment by Idrinth** [comment]
you're welcome @pskmsc :)
