### ISSUE TITLE
Missing WAR.exe on the Folder [Linux]

### ISSUE THREAD

**Issue by xpander69** [Idrinth/WARAddonClient#90]
![ss_30012020_12 48 37](https://user-images.githubusercontent.com/1345116/73443261-0864cf80-435f-11ea-950a-70a8cf3bdbcf.png)

Basically it can't find the location under Linux. I dont know much about Java, but is it possible to add a option where you manually browse to the Addon folder and it can pick up from there?

**Comment by xpander69** [comment]
Ohh never mind, sorry it works fine when starting from command line... odd

![ss_30012020_12 52 05](https://user-images.githubusercontent.com/1345116/73443477-62fe2b80-435f-11ea-99ff-47e2d0d74565.png)

Closing the bug.. you didnt see anything.

**Comment by Idrinth** [comment]
Will have a look for both the bug and feature once I'm back and able, may take a month or two.
Thank you for using the tool.

**Comment by xpander69** [comment]
The bug is probably just a linux thing. have to start in the same folder to make it work
so i made a script into WAR folder to start, and it works great like that

```
#!/bin/bash
# Go into the directory
BINDIR="$(dirname "$(readlink -fn "$0")")"
cd "$BINDIR"

# Start the Addon Manager with Java
java -jar ./WARAddonClient.jar
```

Thank you for the nice tool!

The feature could still be useful, to be able to select the Addon folder.

**Comment by Idrinth** [comment]
done with 1.9.0
